### ISSUE TITLE
为什么配置好后，显示Object not found

### ISSUE THREAD

**Issue by Humecry** [phalapi/fast-route#1]
**对http://localhost/site/index进行访问出现：**
Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404
localhost
Apache/2.4.18 (Unix) OpenSSL/1.0.2h PHP/5.6.23 mod_perl/2.0.8-dev Perl/v5.16.3

**Comment by phalapi** [comment]
感觉应该是apache配置得不对，没有配置支持隐藏index.php

**Comment by Humecry** [comment]
是的，这里有人提供解决方法：http://qa.phalapi.net/?/question/134#!answer_form
